---
title: "Geisinger Analysis"
author: "Andrew Zimolzak"
date: "2023-02-26"
output: word_document
---

# Setup

```{r packages, message=FALSE, warning=FALSE}
library(dplyr)
library(knitr)
```


```{r input}
X0 = read.csv("EP-DU-1-26-22.csv")
dim(X0)
```

```{r input-lung}
L0 = read.csv("final lung EP for Houston de-id 3-28-22.csv")
dim(L0)
```


## Inspect and edit colnames

```{r include=FALSE}
colnames(X0)
```


```{r my-colnames, include=FALSE}
my_colnames <- c(
  "id",
"age",
"gender",
"race",
"ethn",
"date1",
"ca.type",
"stage",
"date2",
"true.ed",
"true.ed.other",
"true.dx",
"true.dx.other",
"setting",
"setting.other",
"sig.ida",
"sig.obstr",
"sig.blood",
"sig.abdmass",
"sig.rectmass",
"sig.caliber",
"sig.scope",
"sig.fobt",
"sig.flex",
"sig.barium",
"sig.ct",
"sig.fhx",
"sig.massexam",
"sig.other",
"sig.othertext",
"signalwascc",
"signalwascc.other",
"followup",
"followup.other",
"typeep",
"typeep.other",
"cscope.prior",
"cscope.prior.date",
"cscope.prior.results",
"cscope.declined",
"redflags",
"redflags.mult",
"redflags.earliest",
"redflags.other",
"redflags.date",
"dx.init",
"dx.complete",
"cancer.dx.considered",
"outside.care",
"mod",
"delay.requesting",
"delay.completing",
"pt.delay",
"pt.adhere",
"pt.other",
"pt.othertext",
"ppe.hx",
"ppe.exam",
"ppe.ordering",
"ppe.documentation",
"ppe.integration",
"ppe.other",
"ppe.othertext",
"tests.notdone",
"tests.donewrong",
"tests.interpwrong",
"tests.misident",
"tests.other",
"tests.othertext",
"follow.timely",
"follow.scheduling",
"follow.returnresults",
"follow.reviewresults",
"follow.documenting",
"follow.monitorpt",
"follow.other",
"follow.othertext",
"refer.init",
"refer.action",
"refer.communication",
"refer.other",
"refer.othertext",
"summary",
"complete"
)

```

```{r assign-colnames}
length(my_colnames)
colnames(X0) <- my_colnames
```

# CRC Results

## Overly complex crosstables

```{r tabulate-ppv}
table(was.ed.encounter = X0$true.ed, new.ca.dx.30d = X0$true.dx)
```

```{r tabulate-mod}
table(mod.status = X0$mod, had.redflag.prior = X0$redflags)
```

## Tidy some cell values

```{r casewhen}
X0 %>%
  mutate(typeep = case_when(
    typeep == "Cancer diagnosed during the emergency visit or inpatient stay (including direct admits from PCP or ED)" ~ "Route A during",
    typeep == "Cancer diagnosed in a related, <b>separate</b> encounter following a cancer-related-emergency event" ~ "Route B after cancer visit",
    typeep == "Cancer diagnosed in a related, separate encounter following a <b>non-cancer</b>-related-emergency event" ~ "Route C after noncancer visit",
    typeep == "Cancer diagnosed in an <b>unrelated</b>, separate encounter following a non-cancer-related-emergency event" ~ "Route D unrelated",
    TRUE ~ typeep
  )) -> X1
```

## Useful tables

```{r table-of-type}
addmargins(table(X1$typeep))
```

```{r just-mod}
addmargins(table(X1$mod))
```

# Lung results

TBD.
